### ISSUE TITLE
Google's tabs box sizing changed from default to "border-box"

### ISSUE THREAD

**Issue by omrilotan** [DCookieMonster/stack-search#1]
![screen shot 2017-05-30 at 10 29 51](https://cloud.githubusercontent.com/assets/516342/26572569/1f8fdd5e-4523-11e7-8cdd-8280bb68197a.png)

Source (part of `bootstrap.min.css`):
![image](https://cloud.githubusercontent.com/assets/516342/26572627/54be3d54-4523-11e7-93eb-7e9dffb3b933.png)

**Comment by amirdor** [comment]
fix in version 1.3.1
