### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by asafofer** [DCookieMonster/stack-search#12]
I've noticed that the extension had stopped working

details:
OS win 10 64 bit
chrome version 63.0.3239.132

**Comment by doramir** [comment]
@asafofer fixed on  v1.9.0
I published it, it will be available in 1 hour give or take
Thanks for reporting the issue!

the issue was that Google change something in the search results and the regex stop working

**Comment by asafofer** [comment]
thank you very much! works perfectly.
amazing extension
