### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by baruchiro** [DCookieMonster/stack-search#13]
Ubuntu 17.10
Firefox 58.0.2

**Comment by Bezbran** [comment]
I'm also experiencing this issue.

Windows 10
Chrome 64.0.3282.167

**Comment by doramir** [comment]
checking the issue and will updated soon as it resolved and there is a new version  :) 
thanks!

**Comment by doramir** [comment]
fixed in version 2
there was a change with one of the HTML tag on stack exchange sites

**Comment by Bezbran** [comment]
TNX!

**Comment by baruchiro** [comment]
Still not work on firefox 58

**Comment by baruchiro** [comment]
Windows 10:

- Firefox Developer Edition 60.0b11 x64: **Not work**.
- Chrome 65.0.3325.181 x64: **Work**.

Ubuntu 10.10:

- Firefox Quantum 59.0.2 x64: **Not work**.
- Chromium 65.0.3325.181: **Work**.
