### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by shirulaf** [DCookieMonster/stack-search#15]
Hi, 

It appears that the extension stopped working.
The "loading dots" appears, but then dissapear without showing the extension elements at all.

Thanks a lot, 
Amazing Extension!

![image](https://user-images.githubusercontent.com/25006652/50420396-ca81a780-083e-11e9-98a6-b966b5732911.png)
-----------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/25006652/50420403-d66d6980-083e-11e9-9a4e-7f5816c13dab.png)

**Comment by doramir** [comment]
fixed in the current version! will be published soon 
the problem was a change in stackoverflow site
