### ISSUE TITLE
Search from address bar not working

### ISSUE THREAD

**Issue by shmoltz** [DCookieMonster/stack-search#3]
Works only when you search from the search box on google results page.
(p.s. Great job!!)

**Comment by amirdor** [comment]
@shmoltz which Google domain (.com? .co.il?), do you have ad block installed?

**Comment by shmoltz** [comment]
co.il
Yes 3 types of ad block...

**Comment by amirdor** [comment]
@shmoltz try to stop AdBlock and search. tell me if it work. 10x

**Comment by amirdor** [comment]
I just tried on google.co.il and everything works fine.
can you send me the console log error?
`Open as panel

To open the dedicated Console panel, either:

Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).
If DevTools is already open, press the Console button.`

maybe you are getting an exception

**Comment by shmoltz** [comment]
the only ad block that i have problems is **uBlock Origin** 
with the others works fine!
I think I'll manage without **uBlock Origin**  ;)
