### ISSUE TITLE
Awesome extensions! Feature request though

### ISSUE THREAD

**Issue by nimrodolev** [DCookieMonster/stack-search#7]
Easy to implement (I think) - 
Left and right navigation keys aren't in use in the search page anyway, so it could be nice to bind them and have them scroll between possible answers in addition to using the arrow buttons on the sides.

Thanks!
Nimrod

![keyboards rock!](https://img.memecdn.com/go-home-keyboard_o_949527.webp)

**Comment by amirdor** [comment]
@nimrodavid  It will be in the next version :) 1.6.3
enjoy!
