### ISSUE TITLE
Keyboard navigation preventing arrow keys usage

### ISSUE THREAD

**Issue by Shebo** [DCookieMonster/stack-search#9]
Hi Dor, Thank you for the great extension, it helped me a lot!

I saw you've added a keyboard navigation feature a few days ago (#7)  and wanted to report about a related bug:

The new feature is preventing from the keypress event to bubble up by using `e.preventDefault();`, which in turn is disabling the ability to navigate inside google's search box using the arrow keys, or to side-scroll a narrow window.

My suggestion will be 1 of 2 possibilities, although both of them has their own drawbacks:

1. remove `e.preventDefault();` and let keypress event the bubble up freely (It will hurt the UX since every keystroke will do multiple things at once).
2. Use `( e.target.nodeName == 'INPUT' )` to condition the event prevention and stackoverflow's answers-scroll.
This solution isn't perfect either since It will only solve the search box's use case, and every user could want to use the arrow keys for other stuff.

**Comment by amirdor** [comment]
Ok it will be fixed in the next version today :)
